### ISSUE TITLE
Unable to import library in project

### ISSUE THREAD

**Issue by Julusian** [go-redis/redis_rate#15]
When I attempt to go get the library
```
$ go get gopkg.in/go-redis/rate.v5
package gopkg.in/go-redis/rate.v5: unrecognized import path "gopkg.in/go-redis/rate.v5" (parse https://gopkg.in/go-redis/rate.v5?go-get=1: no go-import meta tags)
```
If I clone via the github url and attempt to use the library I get:
```
code in directory /go/src/github.com/go-redis/redis_rate expects import "gopkg.in/go-redis/rate.v5"
```

So as far as I can tell it is not currently possible to import and use this library

**Comment by vmihailenco** [comment]
Library was renamed from `rate.v5` to `redis_rate.v5` to avoid confusing with `time/rate`. Also gopkg.in support is removed in v6 and you should import `github.com/go-redis/redis_rate`.

**Comment by Julusian** [comment]
Oh ok. I didnt see that there was a v6. I shall use that instead then.

However, v5 is still not importable with that updated url. Might impact anyone who needs to stay with that version
```
$ go get gopkg.in/go-redis/redis_rate.v5
package gopkg.in/go-redis/redis_rate.v5: unrecognized import path "gopkg.in/go-redis/redis_rate.v5" (parse https://gopkg.in/go-redis/redis_rate.v5?go-get=1: no go-import meta tags)
```

**Comment by vmihailenco** [comment]
I am not sure, but it looks like gopkg.in does not like underscore in the name...

**Comment by vmihailenco** [comment]
Yeah, looks like it is considered a bad name for package name - https://github.com/niemeyer/gopkg/issues/41.
