### ISSUE TITLE
rate key lives longer than period of limitation

### ISSUE THREAD

**Issue by sergolius** [go-redis/redis_rate#20]
Is there any reason to keep rate key longer than period(dur) of limitation?
Here is code:
https://github.com/go-redis/redis_rate/blob/e1f625c9ecbdd4c3085dfeb31e09c8e3d5c7cb3f/rate.go#L140

Extra 30 seconds in case of short period limitation may create snowball effect.

**Comment by vmihailenco** [comment]
Mostly because clocks can be out of sync or app can check rate limit slightly later than expected (because of queuing etc).
