### ISSUE TITLE
Support go-redis v9? 

### ISSUE THREAD

**Issue by beihai0xff** [go-redis/redis_rate#77]

**Comment by fantasy9830** [comment]
`go get github.com/go-redis/redis_rate/v10`

`go: module github.com/go-redis/redis_rate@upgrade found (v6.5.0+incompatible), but does not contain package github.com/go-redis/redis_rate/v10`

**Comment by beihai0xff** [comment]
@vmihailenco 
Could you draft a new release with tag v10.0.0-rc.1?

**Comment by jjmengze** [comment]
Hi folks is there any updated ?
it seems already published  v10 branch, but has not tagged 

@vmihailenco

**Comment by jjmengze** [comment]
@vmihailenco v10 branch is already ready, could you please help tagged v10 tag?

thanks

**Comment by jjmengze** [comment]
it seems already tagged ,nice job !!!
https://github.com/go-redis/redis_rate/tree/v10.0.0
